/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shopmanagementsystembyshad.sajid;

import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.Insets;
import java.awt.Toolkit;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.Writer;
import java.sql.Date;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import static shopmanagementsystembyshad.sajid.BuyingStyff.PName;
import static shopmanagementsystembyshad.sajid.BuyingStyff.PPrice;
import static shopmanagementsystembyshad.sajid.BuyingStyff.PQty;
import java.text.SimpleDateFormat;  
import javax.swing.UIManager;
import static shopmanagementsystembyshad.sajid.CustomerInfo.UserPhoneNumber;
import static shopmanagementsystembyshad.sajid.CustomerInfo.Username;

/**
 *
 * @author ASUS
 */
public class CheckoutPage extends javax.swing.JFrame {

    /**
     * Creates new form CheckoutPage
     */
    String[] UserInfo = new String[2];
    float cost = 0;
    float vat=(float)0.0;
    float dis=(float)0.0;
    public CheckoutPage() {
        setPreferredSize(new Dimension(Toolkit.getDefaultToolkit().getScreenSize()));
        initComponents();
        UserInfo[0]=Username;
        UserInfo[1]=UserPhoneNumber;
        getvatordisc g = new getvatordisc();
        vat = g.getvatordiscget("D:/programming/java/224_Project/ShopManagementSystemByShad&Sajid/vat.txt");
        dis = g.getvatordiscget("D:/programming/java/224_Project/ShopManagementSystemByShad&Sajid/Discount.txt");
        showbuy();   
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        button1 = new java.awt.Button();
        jLabel8 = new javax.swing.JLabel();
        button2 = new java.awt.Button();
        jLabel9 = new javax.swing.JLabel();
        price = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Ricit = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 32, 52));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 177, 112));
        jLabel1.setText("SHOP_24.31");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 51));
        jLabel2.setText("Time To");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 177, 112));
        jLabel6.setText("--->--->--->");

        button1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        button1.setLabel("Cancel");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 153, 51));
        jLabel8.setText("Checkout!");

        button2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        button2.setLabel("Purchase");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 153, 102));
        jLabel9.setText("You Have To Pay");

        price.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        price.setForeground(new java.awt.Color(255, 255, 255));
        price.setText("Checkout!");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 51));
        jLabel3.setText("bdt");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(43, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(price)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addGap(88, 88, 88)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addGap(60, 60, 60)
                .addComponent(jLabel9)
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(price)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(75, 75, 75)
                .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );

        jPanel3.setBackground(new java.awt.Color(0, 51, 102));

        Ricit.setColumns(20);
        Ricit.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        Ricit.setRows(5);
        jScrollPane2.setViewportView(Ricit);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Your Reciet!");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 687, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(314, 314, 314)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel4)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(0, 51, 102));
        jPanel4.setLayout(new java.awt.GridBagLayout());
        jScrollPane1.setViewportView(jPanel4);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        BoughtProducts GoToCustomerPurchase = new BoughtProducts();
        GoToCustomerPurchase.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_button1ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
        String s = JOptionPane.showInputDialog(null,"What Did The Customer Pay[ "+cost+"]" ); 
        try{
            float f = Float.parseFloat(s);
            if(f<cost){
                JOptionPane.showMessageDialog(null, "Total Bill is "+cost+". Needs to pay more! Pay Again!");
            }
            else{
                if(cost==f){
                    JOptionPane.showMessageDialog(null, "Purchase Complete");
                    this.dispose();
                    HomePage h = new HomePage();
                    h.setVisible(true);
                }
                else{
                    float back = f-cost;
                    int m = (int)back;
                    int m1000=m/1000;
                    back=back%1000;
                    m = (int)back;
                    int m500=m/500;
                    back=back%500;
                    m = (int)back;
                    int m100=m/100;
                    back=back%100;
                    m = (int)back;
                    int m50=m/50;
                    back=back%50;
                    m = (int)back;
                    int m20=m/20;
                    back=back%20;
                    m = (int)back;
                    int m10=m/10;
                    back=back%10;
                    m = (int)back;
                    int m5=m/5;
                    back=back%5;
                    m = (int)back;
                    int m2=m/2;
                    back=back%2;
                    m = (int)back;
                    int m1 = m;
                    float mpoysa = back-m1;
                    String re="Give the customer :  ";
                    if(m1000!=0){
                        String ss=String.valueOf(m1000);
                        re=re+" "+ss+"-1000 taka notes. ";
                    }
                    if(m500!=0){
                        String ss=String.valueOf(m500);
                        re=re+" "+ss+"-500 taka notes. ";
                    }
                    if(m100!=0){
                        String ss=String.valueOf(m100);
                        re=re+" "+ss+"-100 taka notes. ";
                    }
                    if(m50!=0){
                        String ss=String.valueOf(m50);
                        re=re+" "+ss+"-50 taka notes. ";
                    }
                    if(m20!=0){
                        String ss=String.valueOf(m20);
                        re=re+" "+ss+"-20 taka notes. ";
                    }
                    if(m10!=0){
                        String ss=String.valueOf(m10);
                        re=re+" "+ss+"-10 taka notes. ";
                    }
                    if(m5!=0){
                        String ss=String.valueOf(m5);
                        re=re+" "+ss+"-5 taka notes. ";
                    }
                    if(m2!=0){
                        String ss=String.valueOf(m2);
                        re=re+" "+ss+"-2 taka notes. ";
                    }
                    if(m1!=0){
                        String ss=String.valueOf(m1);
                        re=re+" "+ss+"-1 taka notes. ";
                    }
                    if(mpoysa!=0){
                        String ss=String.valueOf(mpoysa);
                        re=re+" "+ss+"-poosha. ";
                    }
                    UIManager.put("OptionPane.messageFont", new Font("Arial", Font.BOLD, 16));
                    JOptionPane.showMessageDialog(null, re);
                    JOptionPane.showMessageDialog(null, "Purchase Complete");
                    try{
                        if(PName.isEmpty()){
            JOptionPane.showMessageDialog(null,"No Products in the cart");
            return ;
        }
            Writer output;
            String username=UserInfo[0];
            String phnnumber=UserInfo[1];
            output = new BufferedWriter(new FileWriter("D:\\programming\\java\\224_Project\\ShopManagementSystemByShad&Sajid\\purchaseHistory.txt",true));
            java.util.Date date=new java.util.Date();  
            String datetime = String.valueOf(date);
            output.append(datetime+"\n&\n"+username+"---"+phnnumber+"\n&\n");
            float totalcost=(float)0.0;
            editPrd e = new editPrd();
            String Path="D:/programming/java/224_Project/ShopManagementSystemByShad&Sajid/ProductsInformation.csv";
            ReadFile Info = new ReadFile();
        
        int numberOfProducts = Info.ReadProducts(Path);
        String [] NameArray = Info.GetProductNames();
        int [] IdArray = Info.GetProductIds();
        int [] QtyArray = Info.GetPrdQtys();
        float [] BPriceArray = Info.GetPrdBuyingPrices();
        float [] SPriceArray = Info.GetPrdSellingPrices();
        
            for(int i=0;i<PName.size();i++){
                for(int j=0;j<NameArray.length;j++){
                    if(PName.get(i).equals(NameArray[j])){
                        e.edit(Path, NameArray[j], NameArray[j], QtyArray[j]-PQty.get(i), BPriceArray[j], SPriceArray[j]);
                    }
                }
                output.append(PName.get(i)+"-"+String.valueOf(PPrice.get(i))+"x"+String.valueOf(PQty.get(i))+"->"+String.valueOf(PQty.get(i)*PPrice.get(i))+"\n&\n");
                totalcost+=PQty.get(i)*PPrice.get(i);
            }
            totalcost=(1+(vat/100)-(dis/100))*totalcost;
            output.append("VAT="+String.valueOf(vat)+"\n&\n"+"DISCOUNT="+String.valueOf(dis)+"\n&\n");
            output.append("Total Cost : "+String.valueOf(totalcost)+"\n@\n");
            output.close();
            
            
        }
        catch(Exception e){
            e.printStackTrace();
        }
                    this.dispose();
                    HomePage h = new HomePage();
                    h.setVisible(true);                    
                }
            }
        }
        catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Input Invalid");
        }
        
    }//GEN-LAST:event_button2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckoutPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckoutPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckoutPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckoutPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckoutPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Ricit;
    private java.awt.Button button1;
    private java.awt.Button button2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel price;
    // End of variables declaration//GEN-END:variables

    public void showbuy(){
        jPanel4.revalidate();
        jPanel4.repaint();
        BoughtPrd Info = new BoughtPrd();
        GridBagConstraints grid = new GridBagConstraints ();
        grid.insets = new Insets(20,20,20,20); 
        int row=0;
        int col=0;
        int NumberOfItems=0;
        float Cost=0;
        price.setText(Float.toString(Cost));
        if(PName.isEmpty()){
            JOptionPane.showMessageDialog(null,"No Products in the cart");
            return ;
        }
        String Path = "D:/programming/java/224_Project/ShopManagementSystemByShad&Sajid/sales.txt";
        Ricit.append("Shop24.31\n");
        java.util.Date date=new java.util.Date();  
        String s = String.valueOf(date);
        Ricit.append(s+"\n");
        Ricit.append("Name: "+UserInfo[0]+"\n");
        Ricit.append("Phone Number: "+UserInfo[1]+"\n");
        Ricit.append("--------------------------------------------\n");
        for(int i=0;i<PName.size();i++){
            Ricit.append(PName.get(i)+"\t");
            if(PName.get(i).length()<=7){
                Ricit.append("\t");
            }
            Ricit.append(String.valueOf(PPrice.get(i))+" x"+String.valueOf(PQty.get(i))+"\t"+String.valueOf(PQty.get(i)*PPrice.get(i))+"\n");
            NumberOfItems+=PQty.get(i);
            Cost+=(PQty.get(i)*PPrice.get(i));
            CheckoutProduct p = new CheckoutProduct(PName.get(i), PPrice.get(i), PQty.get(i));
            jPanel4.add(p,grid);
            row++;
            if(row==1){
                col++;
                row=0;
            }            
            grid.gridx=row;
            grid.gridy=col;
        }       
        Ricit.append("--------------------------------------------\n");
        
        Ricit.append("VAT:\t\t"+String.valueOf(vat)+"%\n");
        Ricit.append("Discount:\t\t"+String.valueOf(dis)+"%\n");
        Ricit.append("--------------------------------------------\n");
        Cost=(1+(vat/100)-(dis/100))*Cost;
        cost=Cost;
        Ricit.append("Total Cost:\t\t"+String.valueOf(Cost)+"bdt\n");
        price.setText(Float.toString(Cost));
        Ricit.append("Thanks For Shpping With Us!");
        getvatordisc g = new getvatordisc();
        float f = g.getvatordiscget(Path);
        f+=Cost;
        try{    
                FileWriter fw=new FileWriter(Path);    
                fw.write(String.valueOf(f));    
                fw.close();  
                System.out.println("Price Updated");
                
            }
            catch(Exception e){
                System.out.println(e);
            }
}
}
