/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shopmanagementsystembyshad.sajid;

import javax.swing.JOptionPane;
import static shopmanagementsystembyshad.sajid.BuyingStyff.PName;
import static shopmanagementsystembyshad.sajid.BuyingStyff.PPrice;
import static shopmanagementsystembyshad.sajid.BuyingStyff.PQty;


/**
 *
 * @author ASUS
 */
public class CutomerPrd extends javax.swing.JPanel {

    /**
     * Creates new form CutomerPrd
     */
    public CutomerPrd() {
        initComponents();
    }
    public void SetName(String s){
        PrdName.setText(s);
    }
    public void SetPrice(float pr){
        PrdSellingPrice.setText(String.valueOf(pr));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PrdName = new javax.swing.JLabel();
        PrdId = new javax.swing.JLabel();
        PrdSellingPrice = new javax.swing.JLabel();
        PrdId2 = new javax.swing.JLabel();
        button1 = new java.awt.Button();
        button2 = new java.awt.Button();

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        PrdName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        PrdName.setForeground(new java.awt.Color(255, 255, 255));
        PrdName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PrdName.setText("jLabel1");

        PrdId.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        PrdId.setForeground(new java.awt.Color(255, 255, 255));
        PrdId.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        PrdId.setText("Name");

        PrdSellingPrice.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        PrdSellingPrice.setForeground(new java.awt.Color(255, 255, 255));
        PrdSellingPrice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PrdSellingPrice.setText("jLabel1");

        PrdId2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        PrdId2.setForeground(new java.awt.Color(255, 255, 255));
        PrdId2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        PrdId2.setText("Price");

        button1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        button1.setLabel("Add To Cart");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        button2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        button2.setLabel("Remove");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(PrdId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addComponent(PrdName, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(PrdId2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PrdSellingPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PrdId)
                    .addComponent(PrdName))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PrdId2)
                    .addComponent(PrdSellingPrice))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        int available=0;
        ReadFile r = new ReadFile();
        String Path ="D:/programming/java/224_Project/ShopManagementSystemByShad&Sajid/ProductsInformation.csv";
        int n=r.ReadProducts(Path);
        String[] names = r.GetProductNames();
        int[] qtys = r.GetPrdQtys();
        for(int i=0;i<n;i++){
            //System.out.println(PName.get(i)+" "+PQty.get(i));
            if(PrdName.getText().equals(names[i])){
                available = qtys[i];
            }
        }
        if(available==0){
            JOptionPane.showMessageDialog(null, "The Product Is Out Of Stock!");
            return ;
        }
        if(PName.isEmpty()){
            PName.add(PrdName.getText());
            PPrice.add(Float.parseFloat(PrdSellingPrice.getText()));
            PQty.add(1);
            System.out.println("Added "+PrdName.getText());
        }
        else{
            for(int i=0;i<PName.size();i++){
                String name = String.valueOf(PName.get(i));
                if(name.equals(PrdName.getText())){
                    int qty = PQty.get(i).intValue();
                    PQty.set(i,qty+1);
                    System.out.println("Added "+name);
                    break;
                }
                else{
                    if(i==PName.size()-1){
                        PName.add(PrdName.getText());
                        PPrice.add(Float.parseFloat(PrdSellingPrice.getText()));
                        PQty.add(1);
                        System.out.println("Added "+PrdName.getText());
                        break;
                    }
                }
            //System.out.println(PName.get(i));
            }
        }
        //System.out.println("--------------------------");
    }//GEN-LAST:event_button1ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
        if(PName.size()==0){
            JOptionPane.showMessageDialog(null, "You Haven't Added Any Product");
        }
        else{
        for(int i=0;i<PName.size();i++){
            String name = String.valueOf(PName.get(i));
            if(name.equals(PrdName.getText())){
                int qty = PQty.get(i).intValue();
                if(qty>0){
                    PQty.set(i,qty-1);
                    System.out.println("Quantity Reduced "+PName.get(i));
                    if(PQty.get(i)==0){
                        PQty.remove(i);
                        PName.remove(i);
                        PPrice.remove(i);
                        System.out.println("Removed "+PName.get(i));
                    }
                    break;
                }
                
            }
            else{
                if(i==PName.size()-1){
                    JOptionPane.showMessageDialog(null, "You Haven't Added This Products");
                    break;
                    }
         
            }
        }}
    }//GEN-LAST:event_button2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PrdId;
    private javax.swing.JLabel PrdId2;
    private javax.swing.JLabel PrdName;
    private javax.swing.JLabel PrdSellingPrice;
    private java.awt.Button button1;
    private java.awt.Button button2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
